const COMMANDS = [
  "help",
  "local-auth",
  "list-profiles",
  "create-profile",
  "get-profile",
  "delete-profile",
  "bulk-delete-profiles",
  "bulk-create-profiles",
  "transfer-profiles",
  "share-profile-access",
  "share-profiles-access",
  "list-profile-statuses",
  "get-profile-status",
  "create-profile-status",
  "update-profile-status",
  "delete-profile-status",
  "bulk-delete-profile-statuses",
  "bulk-change-profile-statuses",
  "list-folders",
  "create-folder",
  "get-folder",
  "update-folder",
  "delete-folder",
  "reorder-folders",
  "attach-profiles-to-folder",
  "detach-profiles-from-folders",
  "list-folder-profile-ids",
  "list-extensions",
  "create-extension",
  "delete-extensions",
  "upload-extension-zip",
  "list-homepages",
  "create-homepages",
  "update-homepage",
  "delete-homepages",
  "list-bookmarks",
  "create-bookmark",
  "update-bookmark",
  "delete-bookmarks",
  "list-team-users",
  "create-team-user",
  "update-team-user",
  "delete-team-user",
  "export-local-storage",
  "export-local-storage-mass",
  "import-local-storage",
  "import-cookies",
  "export-cookies",
  "run-cookie-robot",
  "stop-cookie-robot",
  "list-running-profiles",
  "start-profile",
  "stop-profile",
  "update-profile",
  "open-url",
  "list-proxies",
  "get-proxy",
  "create-proxy",
  "update-proxy",
  "delete-proxy",
  "assign-proxy-to-profile",
  "check-proxy",
  "change-proxy-ip",
  "change-profile-proxy-ip",
  "raw-cloud",
  "raw-local",
];

function buildHelpText() {
  return [
    "Commands:",
    ...COMMANDS.map((command) => `  ${command}`),
    "",
    "Protected local endpoints auto-use LocalSessionToken from:",
    "  1. --local-session-token",
    "  2. DOLPHIN_ANTY_LOCAL_SESSION_TOKEN",
    "  3. .runtime/local-session-token.txt",
    "",
    "Refresh cached LocalSessionToken:",
    "  node ./scripts/get-local-session-token.js",
    "",
    "Examples:",
    '  node ./scripts/dolphin-anty.js --command list-profiles --query "shop"',
    `  node ./scripts/dolphin-anty.js --command create-profile --json '{"name":"QA Profile","platform":"windows","browserType":"anty"}'`,
    '  node ./scripts/dolphin-anty.js --command start-profile --profile-id "123456"',
    '  node ./scripts/dolphin-anty.js --command update-profile --profile-id "123456" --set "name=QA Profile"',
    '  node ./scripts/dolphin-anty.js --command upload-extension-zip --file-path "/tmp/ext.zip"',
    '  node ./scripts/dolphin-anty.js --command check-proxy --proxy-id "98765"',
  ].join("\n");
}

module.exports = {
  COMMANDS,
  buildHelpText,
};
